spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:file:/tmp/real
    username: sa
    password:
    driver-class-name: org.h2.Driver
  thymeleaf:
    cache: false
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect

  servlet:
    multipart:
      enabled: true
      location: /tmp
      max-request-size: 30MB
      max-file-size: 10MB

  mvc:
    path-match:
      matching-strategy: ant_path_matcher
#  security:
#    user:
#      name: admin
#      password: 1234

upload:
  path: upload

logging:
  pattern:
    file: "%-4relative [%thread] %-5level %logger{35} - %msg%n"
  logback:
    rolling policy:
      file-name-pattern: "${LOG_FILE}.%d{yyyy-MM-dd}_%i.zip"
      max-history: 7
      max-file-size: 5KB
      total-size-cap: 1MB
  file:
    name: logs-prod
  level:
    root: error